// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#include "i18n.h"
#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x6_3(
        KC_TRANSPARENT, KC_Q,           LT(4,KC_W),     KC_F,    LT(2,KC_P),     KC_B,                   KC_J,           LT(3,KC_L),     LT(1,KC_U),     LT(5,DE_Y),     DE_SLSH,       KC_TRANSPARENT,
        KC_TRANSPARENT, KC_A,           KC_R,           KC_S,           KC_T,           KC_G,                   KC_M,           KC_N,           KC_E,           KC_I,           KC_O,          KC_TRANSPARENT,
        KC_TRANSPARENT, MT(MOD_LGUI, DE_Z),MT(MOD_LCTL, KC_X),MT(MOD_LALT, KC_C),KC_D,  KC_V,                   KC_K,           KC_H,           MT(MOD_LALT, KC_COMMA),MT(MOD_RCTL, KC_DOT),MT(MOD_LGUI, DE_MINS), KC_TRANSPARENT,
        KC_TRANSPARENT, LT(6,KC_SPACE), KC_ENTER,                                                               KC_TRANSPARENT, MT(MOD_LSFT, KC_BSPC),OSL(7)
    ),

    [1] = LAYOUT_split_3x6_3(
        KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_PAGE_UP,     DE_GRV,         KC_TRANSPARENT,         KC_TRANSPARENT, KC_LEFT_GUI,    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,
        KC_TRANSPARENT, KC_LEFT,        KC_UP,          KC_DOWN,        KC_RIGHT,       KC_TRANSPARENT,         KC_TRANSPARENT, KC_LEFT_CTRL,   KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,
        KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_PGDN,        KC_TAB,         KC_TRANSPARENT,         KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,
        KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT
    ),

    [2] = LAYOUT_split_3x6_3(
        KC_TRANSPARENT, KC_TRANSPARENT, DE_ASTR,        DE_AMPR,        KC_TRANSPARENT, KC_TRANSPARENT,         KC_TRANSPARENT, DE_UNDS,        DE_PIPE,        DE_QUOT,        KC_TRANSPARENT, KC_TRANSPARENT,
        KC_TRANSPARENT, DE_CIRC,        KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,         DE_HASH,        DE_MINS,        DE_SLSH,        DE_DQUO,        DE_DLR,         KC_TRANSPARENT,
        KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,         KC_TRANSPARENT, DE_TILD,        DE_BSLS,        DE_GRV,         KC_TRANSPARENT, KC_TRANSPARENT,
        KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT
    ),

    [3] = LAYOUT_split_3x6_3(
        KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, DE_LABK,        DE_RABK,        KC_TRANSPARENT,         KC_TRANSPARENT, KC_TRANSPARENT, DE_EQL,         DE_PLUS,        KC_TRANSPARENT, KC_TRANSPARENT,
        KC_TRANSPARENT, DE_LCBR,        DE_RCBR,        DE_LPRN,        DE_RPRN,        DE_AT,                  KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, DE_PERC,        KC_TRANSPARENT,
        KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, DE_LBRC,        DE_RBRC,        KC_TRANSPARENT,         KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,
        KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT
    ),

    [4] = LAYOUT_split_3x6_3(
        KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, LALT(KC_LEFT_CTRL),KC_TRANSPARENT, KC_TRANSPARENT,      KC_TRANSPARENT, KC_F9,          KC_F10,         KC_F11,         KC_F12,KC_TRANSPARENT,
        KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_ESCAPE,      KC_TRANSPARENT,         KC_TRANSPARENT, KC_F5,          KC_F6,          KC_F7,          KC_F8, KC_TRANSPARENT,
        KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,         KC_TRANSPARENT, KC_F1,          KC_F2,          KC_F3,          KC_F4, KC_TRANSPARENT,
        KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT
    ),

    [5] = LAYOUT_split_3x6_3(
        KC_TRANSPARENT, KC_KP_SLASH,    KC_7,           KC_8,           KC_9,           KC_KP_PLUS,             KC_TRANSPARENT, KC_TRANSPARENT, KC_DOT,         KC_TRANSPARENT, KC_TRANSPARENT,KC_TRANSPARENT,
        KC_TRANSPARENT, KC_0,           KC_1,           KC_2,           KC_3,           KC_KP_MINUS,            KC_TRANSPARENT, KC_COMMA,       KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,KC_TRANSPARENT,
        KC_TRANSPARENT, KC_KP_ASTERISK, KC_4,           KC_5,           KC_6,           KC_KP_EQUAL,            KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,KC_TRANSPARENT,
        KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT
    ),

    [6] = LAYOUT_split_3x6_3(
        KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,         KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_DELETE,KC_TRANSPARENT,
        KC_TRANSPARENT, KC_ESCAPE,      KC_ENTER,       DE_QUES,        DE_EXLM,        KC_TRANSPARENT,         KC_TRANSPARENT, DE_ADIA,        DE_UDIA,        DE_ODIA,        DE_SS,    KC_TRANSPARENT,
        KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,         KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,  KC_TRANSPARENT,
        KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT
    ),

    [7] = LAYOUT_split_3x6_3(
        KC_TRANSPARENT, QK_BOOT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,         KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,
        KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,         KC_TRANSPARENT, KC_VOLD, KC_VOLU, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,
        KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,         KC_TRANSPARENT, KC_MEDIA_PREV_TRACK,KC_MEDIA_PLAY_PAUSE,KC_MEDIA_NEXT_TRACK,KC_TRANSPARENT, KC_TRANSPARENT,
        KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT
    ),
};


uint16_t get_tapping_term(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case MT(MOD_LSFT, KC_BSPC):
            return TAPPING_TERM *0.8;
        default:
            return TAPPING_TERM;
    }
}
